### ISSUE TITLE
roadmap to publishing Zenny

### ISSUE THREAD

**Issue by aganter** [ZEN-universe/ZEN-garden#417]
### Organizational stuff
- [x] What is our timeline? 
    - [x] create Gantt chart and set milestones with minimum viable products
    - [x] assign tasks 
    - [x] Decide on publication date (have Github Repo and Read the docs published before) 
- [x] What is our target journal? Should we go for a journal that specifically publishes open source software?
- [x] Do we want to have outside people contributing to the code? How much maintenance do we offer to people contributing? 

### Documentation
- [x] read-the-docs documentation 
    - [x] collect the existing discussions and documentations 
    - [x] What are the required steps to run the model? -> Set up a structure of the Read the docs with useability in mind
- [x] clean-up discussion forum
- [x] publicly accessible version of Zenny vs. "our" version, which is under development and may contain unpublished work? 
     - I think there is the option of having two repos, one public, and one for development such that we can release new versions to the public repo as we like 

### Functionality
- [x] pip and conda installer
- [x] Visualization
- [x] Set up GitHub pipeline (CI)
- [x] Hosting the server and Github after publication? Where? Does ETH have infrastructure for such things? 
- [x] Data hosting

**Comment by aganter** [comment]
@jacob-mannhardt should we close this issue and move open points, which we still want to tackle to their own issues?

**Comment by jacob-mannhardt** [comment]
I think there aren't any open tasks - we've done everything
